#!/usr/bin/env tsx
// Snapshots the AI Collective's public chapter list into
// src/app/components/stacks/scene/aicChapters.ts, the generated module the
// About globe reads for its chapter marks. Same idea as public/data/github.json:
// a committed fallback rather than a build artifact. Nothing checks its
// freshness, so rerun this when chapters open or move.
//
//   pnpm generate:aic-chapters
//
// The endpoint is the same one aicollective.com's own chapters page reads
// (src/server/api/routers/chapters.ts in the website repo). It needs no token.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ENDPOINT = "https://platform.aicollective.com/api/public/chapters";
const OUTPUT_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../src/app/components/stacks/scene/aicChapters.ts",
);

type PlatformChapter = {
  id: string;
  name: string;
  visible: boolean;
  latitude: number | null;
  longitude: number | null;
};

function round(value: number, places: number) {
  const factor = 10 ** places;
  return Math.round(value * factor) / factor;
}

try {
  const response = await fetch(ENDPOINT);
  if (!response.ok) throw new Error(`${ENDPOINT} returned ${response.status}.`);
  const chapters = (await response.json()) as PlatformChapter[];
  const marks = chapters
    .filter(
      (chapter) =>
        chapter.visible &&
        typeof chapter.latitude === "number" &&
        typeof chapter.longitude === "number" &&
        Number.isFinite(chapter.latitude) &&
        Number.isFinite(chapter.longitude),
    )
    .map((chapter) => ({
      // The slug the site's chapter pages are keyed by.
      id: chapter.id,
      name: chapter.name.trim(),
      // Two decimals is about a kilometre, which is well under a texel on
      // the ball; it also keeps the module small.
      lat: round(chapter.latitude!, 2),
      lon: round(chapter.longitude!, 2),
    }))
    .sort((a, b) => a.name.localeCompare(b.name, "en"));

  const date = new Date().toISOString().slice(0, 10);
  const lines = marks.map(
    (mark) =>
      `  { id: ${JSON.stringify(mark.id)}, name: ${JSON.stringify(mark.name)}, lat: ${mark.lat}, lon: ${mark.lon} },`,
  );
  const source = [
    `// Generated by scripts/generate/aic-chapters.ts from ${ENDPOINT}`,
    `// on ${date}: ${marks.length} of ${chapters.length} chapters had coordinates.`,
    "// Do not hand-edit; rerun `pnpm generate:aic-chapters`.",
    "export type AicChapter = Readonly<{",
    "  /** Slug of the chapter's page on aicollective.com. */",
    "  id: string;",
    "  name: string;",
    "  lat: number;",
    "  lon: number;",
    "}>;",
    "",
    "export const AIC_CHAPTERS: readonly AicChapter[] = [",
    ...lines,
    "];",
    "",
  ].join("\n");
  writeFileSync(OUTPUT_PATH, source);
  execFileSync("pnpm", ["exec", "prettier", "--write", OUTPUT_PATH], {
    stdio: "ignore",
  });
  console.log(
    `Wrote aicChapters.ts: ${marks.length} chapters with coordinates (${chapters.length} fetched).`,
  );
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
}
