/**
 * Shared daylight-identity pieces for the hand-run routine and manual OG
 * cards. The palette and skyline are single-sourced from
 * src/lib/og/daylight.tsx (the runtime OG kit); this file adds the baked
 * cloud tile, which only the build-time cards can afford to embed.
 */
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import React from "react";

import { DAYLIGHT, skyline } from "../../src/lib/og/daylight";

export { DAYLIGHT, skyline };

const CLOUDS_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../public/images/daylight-clouds.png",
);
// Generated by scripts/generate/sky-clouds.ts; dimensions read from the PNG
// header so a regenerated layer can't silently distort here.
const CLOUDS_BUF = readFileSync(CLOUDS_PATH);
const CLOUDS_URI = `data:image/png;base64,${CLOUDS_BUF.toString("base64")}`;
const CLOUDS_ASPECT = CLOUDS_BUF.readUInt32BE(20) / CLOUDS_BUF.readUInt32BE(16);

/** Sky band with the ember glow, clouds, and skyline, spanning the card. */
export function skyBand(width: number, height: number) {
  return React.createElement(
    "div",
    {
      style: {
        position: "relative" as const,
        display: "flex",
        width: "100%",
        height,
        background: `linear-gradient(180deg, ${DAYLIGHT.skyTop} 0%, ${DAYLIGHT.skyMid} 62%, ${DAYLIGHT.skyLow} 100%)`,
      },
    },
    // Ember at 91%: the dome anchors its glow at azimuth -1.15, 91% across
    // the strip's window
    React.createElement("div", {
      style: {
        position: "absolute" as const,
        left: 0,
        right: 0,
        bottom: 0,
        height: "100%",
        background: `radial-gradient(55% 65% at 91% 100%, ${DAYLIGHT.skyEmber}d9, ${DAYLIGHT.skyEmber}00 70%)`,
      },
    }),
    // Shader-generated thin daylight clouds, horizon-anchored like the page
    React.createElement("img", {
      src: CLOUDS_URI,
      width,
      height: Math.round(width * CLOUDS_ASPECT),
      style: { position: "absolute" as const, bottom: -1, left: 0 },
    }),
    skyline(width),
    // The same base haze the pages use: the buildings' feet dissolve into
    // the ground instead of ending on a hard baseline
    React.createElement("div", {
      style: {
        position: "absolute" as const,
        left: 0,
        right: 0,
        bottom: 0,
        height: 44,
        background: `linear-gradient(180deg, ${DAYLIGHT.arc0Clear}, ${DAYLIGHT.arc0} 92%)`,
      },
    }),
  );
}
