"use client";

// A worn wooden cutout of Martha's Vineyard, standing in a short slotted base
// beside the lighthouse on the Musings lower shelf. Authored geometry rather
// than a Source Asset: the coastline is extruded from the owner-supplied
// silhouette (./vineyardOutline.ts, regenerated by
// scripts/stacks-vineyard-outline.mjs) and the wood is the shelf's own grain
// texture in a paler, sun-bleached tone, so the piece reads against the plank
// it stands on instead of vanishing into it. The island stands up rather than
// lying flat because the camera sits only ~11° above the lower shelf: a flat
// 0.28-deep piece would foreshorten to five centimetres of nothing.
import Grabbable from "../Grabbable";
import HeldFacing from "../HeldFacing";
import { MUSINGS_LOWER_LAYOUT } from "../musingsShelfGeometry";
import { WoodMaterial } from "../primitives";
import { RoundedBox } from "@react-three/drei";
import { useEffect, useMemo } from "react";
import * as THREE from "three";

import { VINEYARD_OUTLINE } from "./vineyardOutline";

/** Shared with the Musings layout and its tests. */
export const MUSINGS_VINEYARD_CUTOUT_POSE = {
  base: [MUSINGS_LOWER_LAYOUT.cutoutX, 0, -0.2],
  /** Coast-to-coast width across the shelf: a 21 cm piece at 2 u/m. */
  width: 0.42,
  /** Backward lean out of the slot, radians. Upright reads as a sign; a
   * slight lean reads as a thing someone stood there. */
  lean: 0.1,
  /** Roll of the island in its own plane, radians (negative = clockwise,
   * east end down). The south shore climbs 0.073 units from the Squibnocket
   * lobe to Chappaquiddick when north is dead up, and a slotted stand under
   * a north-up island left the whole east half hanging in air ("make sure
   * the Martha's Vineyard isn't floating", 2026-08-22). Eight degrees brings
   * the east end down onto the slot; the concave middle still arches ~1 cm
   * real above it, which is what a cutout resting on its two low points
   * does. Measured over the outline's lower envelope, not eyeballed. */
  roll: -0.14,
} as const;

export const KATAMA_HOME_DOOR = Object.freeze({
  href: "https://maps.app.goo.gl/Hw3CoQwEEiswVNPK6",
  doorLabel: "Open 490 Katama Road in Google Maps",
});

/** 490 Katama Road projected into the same normalized island bounds used by
 * the owner-supplied coastline. The source map resolves to
 * 41.3526453, -70.5120655; this lands just inland from South Beach. */
export const KATAMA_HOME_ISLAND_POINT = [0.3421, -0.1332] as const;

const VINEYARD_CUTOUT_HOVER_KEY = "grab:vineyard-cutout";
/** 8 mm plywood at the shelf scale. */
const SLAB_THICKNESS = 0.016;
const BEVEL = 0.0025;
/** The slotted foot. Full width now, and tall enough that the slot can
 * swallow 0.03 of the south shore: with the roll above, every point of the
 * coast is then within ~0.02 of the foot's top, so nothing floats. */
const FOOT = { width: 0.46, height: 0.05, depth: 0.07 } as const;
/** How far the slab's lowest point sits below the foot's top surface. */
const SLOT_DEPTH = 0.03;

function rotatedPoint([x, y]: readonly [number, number], roll: number) {
  const cos = Math.cos(roll);
  const sin = Math.sin(roll);
  return [x * cos - y * sin, x * sin + y * cos] as const;
}

/** Match the rotation, scaling, and bounding-box translation applied to the
 * extruded coastline so a geographic marker stays attached to the right spot
 * when the cutout dimensions change. */
export function vineyardSurfacePoint(
  point: readonly [number, number],
  width: number,
  roll: number,
) {
  const outline = VINEYARD_OUTLINE.map((candidate) =>
    rotatedPoint(candidate, roll),
  );
  const xs = outline.map(([x]) => x);
  const ys = outline.map(([, y]) => y);
  const centerX = (Math.min(...xs) + Math.max(...xs)) / 2;
  const floorY = Math.min(...ys);
  const [x, y] = rotatedPoint(point, roll);
  return [(x - centerX) * width, (y - floorY) * width] as const;
}

export const KATAMA_HOME_CUTOUT_POINT = vineyardSurfacePoint(
  KATAMA_HOME_ISLAND_POINT,
  MUSINGS_VINEYARD_CUTOUT_POSE.width,
  MUSINGS_VINEYARD_CUTOUT_POSE.roll,
);

/** Pale, sun-bleached oak for the Musings keepsakes: the cutout's face and
 * foot, and the Trust essay's reading stand, so the two read as one order of
 * lumber rather than two props from two shops. */
export const MUSINGS_OAK = {
  light: { face: "#cdb48e", foot: "#b0946d" },
  dark: { face: "#8b7759", foot: "#6e5c44" },
} as const;

function cutoutGeometry(width: number, roll: number): THREE.ExtrudeGeometry {
  const cos = Math.cos(roll);
  const sin = Math.sin(roll);
  const shape = new THREE.Shape(
    VINEYARD_OUTLINE.map(
      ([x, y]) =>
        new THREE.Vector2(
          (x * cos - y * sin) * width,
          (x * sin + y * cos) * width,
        ),
    ),
  );
  const geometry = new THREE.ExtrudeGeometry(shape, {
    depth: SLAB_THICKNESS,
    steps: 1,
    bevelEnabled: true,
    bevelThickness: BEVEL,
    bevelSize: BEVEL,
    bevelSegments: 1,
  });
  // Lowest point of the coast on local y = 0 (the slot floor), slab centred
  // on x and z, so the lean hinges where the wood meets the foot.
  geometry.computeBoundingBox();
  const box = geometry.boundingBox!;
  geometry.translate(
    -(box.min.x + box.max.x) / 2,
    -box.min.y,
    -(box.min.z + box.max.z) / 2,
  );
  return geometry;
}

export function VineyardCutout({
  unitIndex,
  dark,
  shadeColor,
}: {
  unitIndex: number;
  dark: boolean;
  shadeColor: string;
}) {
  const geometry = useMemo(
    () =>
      cutoutGeometry(
        MUSINGS_VINEYARD_CUTOUT_POSE.width,
        MUSINGS_VINEYARD_CUTOUT_POSE.roll,
      ),
    [],
  );
  useEffect(() => () => geometry.dispose(), [geometry]);
  const theme = dark ? "dark" : "light";
  return (
    <Grabbable
      unitIndex={unitIndex}
      hoverKey={VINEYARD_CUTOUT_HOVER_KEY}
      base={[...MUSINGS_VINEYARD_CUTOUT_POSE.base]}
      shadeColor={shadeColor}
      shadeWidth={0.48}
      shape="box"
      massKg={0.16}
      href={KATAMA_HOME_DOOR.href}
      doorLabel={KATAMA_HOME_DOOR.doorLabel}
    >
      {/* Carried, the island turns square to the camera like the sticker and
          the framed photos do: a silhouette seen edge-on is a stick. */}
      <HeldFacing hoverKey={VINEYARD_CUTOUT_HOVER_KEY}>
        <RoundedBox
          args={[FOOT.width, FOOT.height, FOOT.depth]}
          radius={0.004}
          smoothness={3}
          position={[0, FOOT.height / 2, 0]}
        >
          <WoodMaterial
            hex={MUSINGS_OAK[theme].foot}
            repeat={[1.2, 0.5]}
            roughness={0.8}
          />
        </RoundedBox>
        <group
          position={[0, FOOT.height - SLOT_DEPTH, 0]}
          rotation={[-MUSINGS_VINEYARD_CUTOUT_POSE.lean, 0, 0]}
        >
          {/* ExtrudeGeometry maps cap UVs straight from shape coordinates, so
              the repeat below is per world unit: ~1.4 grain tiles across the
              0.46 width, streaks running west to east. */}
          <mesh geometry={geometry}>
            <WoodMaterial
              hex={MUSINGS_OAK[theme].face}
              repeat={[3, 3]}
              roughness={0.78}
            />
          </mesh>
          <group
            name="490-katama-road-pin"
            position={[
              KATAMA_HOME_CUTOUT_POINT[0],
              KATAMA_HOME_CUTOUT_POINT[1],
              SLAB_THICKNESS / 2 + 0.003,
            ]}
          >
            <mesh
              position={[0, 0.008, 0]}
              rotation={[0, 0, Math.PI]}
              scale={[1, 1, 0.35]}
            >
              <coneGeometry args={[0.009, 0.024, 18]} />
              <meshStandardMaterial
                color="#b9372e"
                roughness={0.42}
                metalness={0.08}
              />
            </mesh>
            <mesh position={[0, 0.022, 0]} scale={[1, 1, 0.3]}>
              <sphereGeometry args={[0.014, 20, 12]} />
              <meshStandardMaterial
                color="#d94c40"
                roughness={0.36}
                metalness={0.1}
              />
            </mesh>
            <mesh position={[0, 0.022, 0.0045]}>
              <circleGeometry args={[0.0048, 18]} />
              <meshStandardMaterial color="#f7dfca" roughness={0.7} />
            </mesh>
          </group>
        </group>
      </HeldFacing>
    </Grabbable>
  );
}
