/** Shared visible dimensions for the two freestanding About marks. */
export const ABOUT_AIC_MARK_HEIGHT = 0.18;
export const ABOUT_AIC_MARK_WIDTH = ABOUT_AIC_MARK_HEIGHT * (700 / 844.38);
export const ABOUT_AIC_BASE_WIDTH = ABOUT_AIC_MARK_WIDTH;
export const ABOUT_AIC_BASE_DEPTH = 0.07;
export const ABOUT_AIC_MARK_SOURCE_DEPTH = 72;
export const ABOUT_AIC_MARK_DEPTH =
  ABOUT_AIC_MARK_SOURCE_DEPTH * (ABOUT_AIC_MARK_HEIGHT / 844.38);

export const ABOUT_APPLE_MARK_HEIGHT = 0.15;
export const ABOUT_APPLE_MARK_WIDTH =
  ABOUT_APPLE_MARK_HEIGHT * (0.4071 - -0.4071);
export const ABOUT_APPLE_BASE_WIDTH = ABOUT_APPLE_MARK_WIDTH;
export const ABOUT_APPLE_BASE_DEPTH = 0.054;
export const ABOUT_APPLE_MARK_DEPTH = 0.015;
