/** Shared authored dimensions for the live and boot Coordination orb. */
export const COORDINATION_PLINTH_SCALE = 0.84;
export const COORDINATION_NECK_SCALE = 0.7;
export const COORDINATION_HORIZON_SCALE = 1.1;
export const COORDINATION_NETWORK_SCALE = 0.9;
export const COORDINATION_GLOBE_PROFILE_WIDTH = 0.21;
export const COORDINATION_GLOBE_PROFILE_HEIGHT = 0.255;
export const COORDINATION_BASE_TOP_RADIUS = 0.071;
export const COORDINATION_BASE_BOTTOM_RADIUS = 0.084;
export const COORDINATION_BASE_HEIGHT = 0.036;
export const COORDINATION_BASE_CENTER_Y = 0.018;
export const COORDINATION_STEM_TOP_RADIUS = 0.027;
export const COORDINATION_STEM_BOTTOM_RADIUS = 0.037;
export const COORDINATION_STEM_HEIGHT = 0.045;
export const COORDINATION_STEM_CENTER_Y = 0.053;
export const COORDINATION_CORE_CENTER_Y = 0.147;
