import type { CommandEntry } from "./types";

export const COMMAND_ENTRIES = [
  {
    id: "destination-home",
    kind: "destination",
    label: "Home",
    aliases: ["chappy", "homepage"],
    keywords: ["start", "world"],
    icon: "house",
    promoted: true,
    target: { kind: "site", site: "home" },
  },
  {
    id: "destination-books",
    kind: "destination",
    label: "Book Notes",
    aliases: ["books", "library", "reading"],
    keywords: ["reviews", "notes", "authors"],
    icon: "books",
    promoted: true,
    target: { kind: "site", site: "books" },
  },
  {
    id: "destination-manual",
    kind: "destination",
    label: "Manual",
    aliases: ["personal manual", "user guide"],
    keywords: ["personality", "values", "working with me"],
    icon: "manual",
    promoted: true,
    target: { kind: "site", site: "manual" },
  },
  {
    id: "destination-routine",
    kind: "destination",
    label: "Routine",
    aliases: ["daily routine", "schedule"],
    keywords: ["morning", "evening", "supplements", "habits"],
    icon: "routine",
    promoted: true,
    target: { kind: "site", site: "routine" },
  },
  {
    id: "destination-weightlifting",
    kind: "destination",
    label: "Weightlifting",
    aliases: ["lifting", "training", "workouts"],
    keywords: ["strength", "exercise", "gym", "personal records"],
    icon: "weightlifting",
    promoted: true,
    target: { kind: "site", site: "weightlifting" },
  },
  {
    id: "section-about",
    kind: "destination",
    label: "About",
    aliases: ["about chappy", "bio"],
    keywords: ["contact", "introduction"],
    icon: "about",
    promoted: true,
    target: { kind: "site", site: "home", hash: "about" },
  },
  {
    id: "section-systems",
    kind: "destination",
    label: "Personal Systems",
    aliases: ["systems"],
    keywords: ["manual", "routine"],
    icon: "systems",
    promoted: true,
    target: { kind: "site", site: "home", hash: "systems" },
  },
  {
    id: "section-projects",
    kind: "destination",
    label: "Projects",
    aliases: ["work", "apps"],
    keywords: ["software", "code", "portfolio"],
    icon: "projects",
    promoted: true,
    target: { kind: "site", site: "home", hash: "projects" },
  },
  {
    id: "section-musings",
    kind: "destination",
    label: "Musings",
    aliases: ["blog", "writing", "articles"],
    keywords: ["medium", "posts", "essays"],
    icon: "musings",
    promoted: true,
    target: { kind: "site", site: "home", hash: "musings" },
  },
  {
    id: "destination-liars-dice",
    kind: "destination",
    label: "Liar's Dice",
    aliases: ["liars dice", "dice calculator"],
    keywords: ["probability", "game", "calculator"],
    icon: "dice",
    promoted: false,
    target: { kind: "site", site: "home", path: "/liarsdice" },
  },
  {
    id: "section-books",
    kind: "destination",
    label: "Book Notes section",
    aliases: ["books section", "reading shelf"],
    keywords: ["homepage", "library"],
    icon: "books",
    promoted: false,
    target: { kind: "site", site: "home", hash: "books" },
  },
  {
    id: "section-weightlifting",
    kind: "destination",
    label: "Weightlifting section",
    aliases: ["training section", "gym section"],
    keywords: ["homepage", "strength"],
    icon: "weightlifting",
    promoted: false,
    target: { kind: "site", site: "home", hash: "weightlifting" },
  },
  {
    id: "action-theme-light",
    kind: "action",
    actionId: "theme-light",
    label: "Set theme to Light",
    aliases: ["light mode"],
    keywords: ["appearance", "theme"],
    icon: "sun",
    promoted: false,
  },
  {
    id: "action-theme-dark",
    kind: "action",
    actionId: "theme-dark",
    label: "Set theme to Dark",
    aliases: ["dark mode"],
    keywords: ["appearance", "theme"],
    icon: "moon",
    promoted: false,
  },
  {
    id: "action-theme-system",
    kind: "action",
    actionId: "theme-system",
    label: "Set theme to System",
    aliases: ["automatic theme"],
    keywords: ["appearance", "theme", "device"],
    icon: "monitor",
    promoted: false,
  },
  {
    id: "action-font-georgia",
    kind: "action",
    actionId: "font-georgia",
    label: "Set font to Georgia",
    aliases: ["georgia pro"],
    keywords: ["typeface", "typography", "font"],
    icon: "serif",
    promoted: false,
  },
  {
    id: "action-font-literata",
    kind: "action",
    actionId: "font-literata",
    label: "Set font to Literata",
    aliases: ["literata font"],
    keywords: ["typeface", "typography", "font"],
    icon: "serif",
    promoted: false,
  },
  {
    id: "action-font-system",
    kind: "action",
    actionId: "font-system",
    label: "Set font to System",
    aliases: ["sans serif", "default font"],
    keywords: ["typeface", "typography", "font"],
    icon: "sans",
    promoted: false,
  },
  {
    id: "action-recents-clear",
    kind: "action",
    actionId: "recents-clear",
    label: "Clear Recent results",
    aliases: ["clear history"],
    keywords: ["recent", "reset", "privacy"],
    icon: "trash",
    promoted: false,
  },
] as const satisfies readonly CommandEntry[];
